---
version: 1.0.0
title: Basisregistratie Adressen en Gebouwen
# shortened title, used in breadcrumb path
serviceIdentifier: BAG
abstract: >-
  This is a description about the dataset in Markdown. See [PDOK BAG dataset](https://www.pdok.nl/introductie/-/article/basisregistratie-adressen-en-gebouwen-ba-1) for details.
# just a dummy picture, but you can put an actual thumbnail here
thumbnail: 3d_thumb.png
resources:
  directory: ./examples/resources
keywords:
  - keyword1
  - keyword2
lastUpdated: "2023-09-08T12:00:00Z"
license:
  name: CC0 1.0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
support:
  name: Example Support
  email: support@example.com
  url: https://support.example.com
# further details of the dataset to be shown on the landing page; supports markdown
datasetDetails:
  - name: Dataset-aanbieder
    value: Kadaster (LV-BAG)
  - name: Kosten afname
    value: Geen
datasetMetadata:
  source: Example Register
  api: https://example.com/my-api/metadata
  dataset: https://example.com/my-dataset/metadata
datasetCatalogUrl: https://www.pdok.nl/datasets
baseUrl: http://localhost:8080
availableLanguages:
  - nl
  - en
# how to serve resources (e.g., images, fonts, sprites). Possible values: directory (serve local files), url (serve through reverse proxy)
ogcApi:
  # which OGC apis to enable. Possible values: tiles, styles, features, maps
  features:
    collections:
      - id: verblijfsobjecten
      - id: panden
      - id: ligplaatsen
      - id: standplaatsen
