---
collectionMetadata: &collectionMetadata
  description: >-
    This is a description about the NewYork collection in Markdown.
    We offer both 3D Tiles and Features for this collection.
  keywords:
    - Keyword1
    - Keyword2
  thumbnail: 3d.png
  lastUpdated: "2023-05-10T12:00:00Z"
  extent:
    srs: EPSG:3857
    bbox: ["-74.391538", "40.435655", "-73.430235", "41.030882"]

version: 1.0.0
title: New York
# shortened title, used in breadcrumb path
serviceIdentifier: New York
abstract: >-
  This is a description about the dataset in Markdown.
thumbnail: 3d.png
resources:
  directory: ./examples/resources
license:
  name: CC0 1.0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
datasetCatalogUrl: https://www.pdok.nl/datasets
baseUrl: http://localhost:8080
ogcApi:
  3dgeovolumes:
    tileServer: https://maps.ecere.com/3DAPI/collections/
    collections:
      - id: NewYork
        # reference to common metadata
        metadata: *collectionMetadata
        tileServerPath: "NewYork/3DTiles"
        uriTemplate3dTiles: "3DTiles/{level}/{x}/{y}.b3m"
        3dViewerUrl: "https://app.pdok.nl/viewer"
  # this is just for demonstration purposes
  features:
    datasource:
      fakedb: true
    collections:
      - id: NewYork
        # reference to common metadata
        metadata: *collectionMetadata
