---
version: 1.0.0
title: Demo of all OGC specs in one API
# shortened title, used in breadcrumb path
serviceIdentifier: DEMO
abstract: >-
  This is example combines features, 3D and vector tiles in one API. Usually
  this would encompass one dataset but this demo uses data from various sources.
  So don't pay too much attention to the actual data. It's just an example/demo
  of GoKoala's capabilities.
# just a dummy picture, but you can put an actual thumbnail here
thumbnail: old.png
resources:
  directory: ./examples/resources
keywords:
  - keyword1
  - keyword2
lastUpdated: "2024-03-04T12:00:00Z"
license:
  name: CC0 1.0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
support:
  name: Example Support
  url: https://support.example.com
# further details of the dataset to be shown on the landing page; supports markdown
datasetDetails:
  - name: Foo
    value: bar
  - name: Costs
    value: None
datasetMetadata:
  source: Example Register
  api: https://example.com/my-api/metadata
  dataset: https://example.com/my-dataset/metadata
datasetCatalogUrl: https://www.pdok.nl/datasets
baseUrl: http://localhost:8080
availableLanguages:
  - nl
  - en
ogcApi:
  tiles:
    title: BGT
    abstract: BGT multi-layer vector tiles
    tileServer: https://api.pdok.nl/lv/bgt/ogc/v1_0/tiles/
    types:
      - vector
    supportedSrs:
      - srs: EPSG:28992
        zoomLevelRange:
          start: 12
          end: 12
      - srs: EPSG:3035
        zoomLevelRange:
          start: 14
          end: 14

  features:
    datasources:
      defaultWGS84:
        geopackage:
          local:
            file: ./examples/resources/addresses-crs84.gpkg
    collections:
      - id: addresses  # same collection as the geovolumes
        metadata:
          title: Addresses
          description: These are example addresses
          extent:
            srs: EPSG:4326
            bbox:
              - 50.2129
              - 2.52713
              - 55.7212
              - 7.37403

  3dgeovolumes:
    tileServer: https://maps.ecere.com/3DAPI/collections/
    collections:
      - id: addresses  # same collection as the tiles
        tileServerPath: "NewYork/3DTiles"
        uriTemplate3dTiles: "3DTiles/{level}/{x}/{y}.b3m"

  styles:
    default: dummy-style
    stylesDir: ./examples/resources
    supportedStyles:
      - id: "dummy-style"
        title: "BGT Standaardvisualisatie"
        description:
          "Een visualisatie voor het gebruik van de BGT/IMGeo-inhoud als hoofdthema,
          die aansluit bij de visualisatie van de Basisregistratie Topografie (BRT).
          In de standaardvisualisatie worden alleen de puntsymbolen voor CADO,
          verkeersdrempel en kering toegepast. Omwille van de visuele hiërarchie wordt
          met klem geadviseerd om de icoonvisualisatie van IMGeo puntobjecten NIET af
          te beelden in combinatie met de standaardvisualisatie."
        keywords:
          - "standaardvisualisatie"
          - "standaard"
          - "pdok"
        lastUpdated: "2023-02-24T11:27:00Z"
        thumbnail: "old.png"
        stylesheets:
          - format: mapbox
          - format: sld10
      - id: "bgt_achtergrondvisualisatie"
        title: "BGT Achtergrondvisualisatie"
        description:
          "Een visualisatie voor het gebruik van de BGT/IMGeo-inhoud als hoofdthema,
          die aansluit bij de visualisatie van de Basisregistratie Topografie (BRT).
          In de achtergrondvisualisatie worden alleen de puntsymbolen voor CADO,
          verkeersdrempel en kering toegepast. Omwille van de visuele hiërarchie wordt
          met klem geadviseerd om de icoonvisualisatie van IMGeo puntobjecten NIET af
          te beelden in combinatie met de achtergrondvisualisatie."
        keywords:
          - "achtergrondvisualisatie"
          - "achtergrond"
          - "pdok"
        pointOfContact: "Beheer PDOK"
        created: "2023-02-24T11:27:00Z"
        updated: "2023-02-24T11:27:00Z"
        license: "MIT"
        scope: "style"
        version: "1.0.0"
        stylesheets:
          - title: "Mapbox Style"
            version: "8"
            specification: "https://docs.mapbox.com/mapbox-gl-js/style-spec/"
            native: true
            link:
              assetFilename: "dummy-style.json"
              rel: "stylesheet"
              type: "application/vnd.mapbox.style+json"
              format: "mapbox"
        links:
          - rel: "preview"
            type: "image/png"
            title: "BGT Achtergrondvisualisatie"
            assetFilename: "old.png"
