---
title: Example Basisregistratie Grootschalige Topografie (BGT)
# shortened title, used in breadcrumb path
serviceIdentifier: BGT
abstract: >-
  This is a description about the dataset in Markdown. See [PDOK BGT dataset](https://www.pdok.nl/introductie/-/article/basisregistratie-grootschalige-topografie-bgt-) for details.
# just a dummy picture, but you can put an actual thumbnail here
thumbnail: bgt_thumb.png
keywords:
  - keyword1
  - keyword2
lastUpdated: "2023-05-08T12:00:00Z"
license:
  name: CC0 1.0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
support: >-
  Support contact point (supports Markdown), e.g. [Email support](mailto:support@example.com)
# further details of the dataset to be shown on the landing page; supports markdown
datasetDetails:
  - name: Dataset-aanbieder
    value: Kadaster (LV-BGT)
  - name: Kosten
    value: Geen
  - name: Metadata dataset
    value: >-
      [Link to metadata](https://example.com/my-dataset/metadata)
baseUrl: http://localhost:8080
# how to serve resources. Possible values: directory (serve local files), url (serve through reverse proxy)
resources:
  directory: ./examples/resources
ogcApi:
  # which OGC apis to enable. Possible values: tiles, styles, features, maps
  tiles:
    title: BGT
    abstract: BGT multi-layer vector tiles
    # base URL to webserver or object storage (e.g. azure blob or S3)
    # which hosts the tiles.
    tileServer:
      https://api.pdok.nl/lv/bgt/ogc/v0_1/tiles/
    # vector tiles and/or raster tiles
    types:
      - vector
    supportedSrs:
      - srs: EPSG:28992
        zoomLevelRange:
          start: 12
          end: 12
