---
version: 1.0.0
title: Basisregistratie Grootschalige Topografie (BGT)
# shortened title, used in breadcrumb path
serviceIdentifier: BGT
abstract: >-
  This is a description about the dataset in Markdown. See [PDOK BGT dataset](https://www.pdok.nl/introductie/-/article/basisregistratie-grootschalige-topografie-bgt-) for details.
# just a dummy picture, but you can put an actual thumbnail here
thumbnail: bgt.png
resources:
  directory: ./examples/resources
keywords:
  - keyword1
  - keyword2
lastUpdated: "2023-09-08T12:00:00Z"
license:
  name: CC0 1.0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
support:
  name: Example Support
  email: support@example.com
  url: https://support.example.com
# further details of the dataset to be shown on the landing page; supports markdown
datasetDetails:
  - name: Dataset-aanbieder
    value: Kadaster (LV-BGT)
  - name: Kosten afname
    value: Geen
datasetMetadata:
  source: Example Register
  api: https://example.com/my-api/metadata
  dataset: https://example.com/my-dataset/metadata
datasetCatalogUrl: https://www.pdok.nl/datasets
baseUrl: http://localhost:8080
availableLanguages:
  - nl
  - en
ogcApi:
  # which OGC apis to enable. Possible values: tiles, styles, features, maps
  features:
    datasource:
      geopackage:
        local:
          file: ./examples/resources/addresses.gpkg
          fid: fid
          queryTimeout: 5s
    collections:
      - id: dutch-addresses
        datasourceId: addresses  # name of the feature table (optional), when omitted collection ID is used.
        metadata:
          title: Dutch Addresses
          description: These are example addresses
          keywords:
            - Building
            - Address
          thumbnail: old.png
          lastUpdated: "2030-01-02T12:00:00Z"
          extent:
            srs: EPSG:4326
            bbox: [ "50.2129", "2.52713", "55.7212", "7.37403" ]
