---
title: PDOK Updater
serviceIdentifier: Updater
abstract: |
  updater conform OGC API Processes
baseUrl: http://localhost:8080
license:
  name: None
  url: https://pdok.nl
ogcApi:
  processes:
    processesServer: http://localhost:8081/ogcapi
    supportsCallback: false
    supportsDismiss: true
