---
title: PDOK Updater
# yamllint disable rule:trailing-spaces
abstract: |
  updater conform OGC API Processes
baseUrl: http://localhost:8080
# yamllint enable rule:trailing-spaces
ogcApi:
  processes:
    processesServer: http://localhost:8081/ogcapi
    supportsCallback: FALSE
    supportsDismiss: TRUE
