---
collectionMetadata: &exampleMetadata
  description: >-
    This is a description about lorum ipsum
  keywords:
    - Keyword1
    - Keyword2
  thumbnail: old.png
  lastUpdated: "2030-01-02T12:00:00Z"
  extent:
    srs: EPSG:3857
    bbox: ["-13512504.4191", "-19500889.3517", "31493617.8353", "19869683.6812"]

version: 1.0.0
title: Basisregistratie Grootschalige Topografie (BGT)
# shortened title, used in breadcrumb path
serviceIdentifier: BGT
abstract: >-
  This is a description about the dataset in Markdown. See [PDOK BGT dataset](https://www.pdok.nl/introductie/-/article/basisregistratie-grootschalige-topografie-bgt-) for details.
# just a dummy picture, but you can put an actual thumbnail here
thumbnail: bgt.png
resources:
  directory: ./examples/resources
keywords:
  - keyword1
  - keyword2
lastUpdated: "2023-09-08T12:00:00Z"
license:
  name: CC0 1.0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
support:
  name: Example Support
  email: support@example.com
  url: https://support.example.com
# further details of the dataset to be shown on the landing page; supports markdown
datasetDetails:
  - name: Dataset-aanbieder
    value: Kadaster (LV-BGT)
  - name: Kosten afname
    value: Geen
datasetMetadata:
  source: Example Register
  api: https://example.com/my-api/metadata
  dataset: https://example.com/my-dataset/metadata
datasetCatalogUrl: https://www.pdok.nl/datasets
baseUrl: http://localhost:8080
availableLanguages:
  - nl
  - en
ogcApi:
  # which OGC apis to enable. Possible values: tiles, styles, features, maps
  features:
    datasource:
      fakedb: true
    collections:
      - id: wegdelen
        metadata:
          # inherit common metadata (to tidy example)
          <<: *exampleMetadata
          title: Wegdelen
      - id: panden
        metadata:
          <<: *exampleMetadata
          title: Panden
      - id: tunneldelen
        metadata:
          <<: *exampleMetadata
          title: Tunneldelen
      - id: waterdelen
        metadata:
          <<: *exampleMetadata
          title: Waterdelen
      - id: spoordelen
        metadata:
          <<: *exampleMetadata
          title: Spoordelen
