
name: deploy web components

on:
  push:
    branches: [ "PDOK-15453-work-in-process-show-patterns" ]
  pull_request:
    branches: [ "PDOK-15453-work-in-process-show-patterns" ]

defaults:
  run:
    working-directory: ./webcomponents/vectortile-view-component

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './webcomponents/vectortile-view-component/package-lock.json'
    - run: npm ci
    - run: npm run deploy
   
  