name: Run Cypress Tests on webcomponents
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    working-directory: ./webcomponents/vectortile-view-component
jobs:
  cypres-ts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./webcomponents/vectortile-view-component/package-lock.json"
      - name: Install
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          working-directory: ./webcomponents/vectortile-view-component
