---
name: test (go)
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup cgo dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev libsqlite3-mod-spatialite

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download
        run: go mod download all

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -shuffle=on ./...

      # we don't (yet) fail on benchmark results, these are just to make sure
      # the benchmarks keep working
      - name: Benchmark
        run: go test -v ./... -bench=. -run=^# -benchmem -count=5

      - name: Generate CRD (for testing)
        run: hack/generate-crd.sh

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: false
          amend: false
          reuse-go: true
        if: |
          github.event_name == 'push'
        continue-on-error: false
