---
name: tidy
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  tidy:
    name: tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - uses: katexochen/go-tidy-check@v2
